### ISSUE TITLE
Create a .travis.yml file 

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Graph-docker#1]
Have the CI check the container:
 - [x] Create the `.travis.yml` ou of e.g. [this example code](https://github.com/VCityTeam/3DTiles-Server-docker/blob/master/.travis.yml)
 - [x] Register this repository to Travis-CI (ask EBO)
 - [x] Add this entry to the UD-SV DashBoard

**Comment by DiegoVinasco** [comment]
wiki link checking is now done through Travis CI [here](https://github.com/VCityTeam/VCity/blob/52b1fdc27b1ebfce55132c74862088bfbaa43dbc/.travis.yml)

dashboard is updated [here](https://github.com/VCityTeam/VCity/blob/master/DashBoard.md)

**Comment by DiegoVinasco** [comment]
The travis CI has been activated. It looks like the repository was already registered in travis. The dashboard was updated as well.
